// Generated by infra/oss/upload-assets.py after signed CDN verification.
export const UI_ASSETS: Record<string, string> = {
  "blink.webp": "bio-v3/assets/f36f433f84351fbf/animations/fox-clerk/blink.webp",
  "environment.webp": "bio-v3/assets/f36f433f84351fbf/animations/fox-clerk/environment.webp",
  "inner-panel.webp": "bio-v3/assets/f36f433f84351fbf/animations/fox-clerk/inner-panel.webp",
  "lingli-avatar.png": "bio-v3/assets/f36f433f84351fbf/animations/fox-clerk/lingli-avatar.png",
  "nod.webp": "bio-v3/assets/f36f433f84351fbf/animations/fox-clerk/nod.webp",
  "note.webp": "bio-v3/assets/f36f433f84351fbf/animations/fox-clerk/note.webp",
  "notebookTalk.webp": "bio-v3/assets/f36f433f84351fbf/animations/fox-clerk/notebookTalk.webp",
  "talk.webp": "bio-v3/assets/f36f433f84351fbf/animations/fox-clerk/talk.webp",
  "wave.webp": "bio-v3/assets/f36f433f84351fbf/animations/fox-clerk/wave.webp",
  "folder.png": "bio-v3/assets/f36f433f84351fbf/desk/folder.png",
  "manuscripts-label.png": "bio-v3/assets/f36f433f84351fbf/desk/manuscripts-label.png",
  "manuscripts.png": "bio-v3/assets/f36f433f84351fbf/desk/manuscripts.png",
  "phone.png": "bio-v3/assets/f36f433f84351fbf/desk/phone.png",
  "delete.svg": "bio-v3/assets/f36f433f84351fbf/materials/delete.svg",
  "felt-oat.webp": "bio-v3/assets/f36f433f84351fbf/materials/felt-oat.webp",
  "lingli-chat-wave.webp": "bio-v3/assets/f36f433f84351fbf/materials/lingli-chat-wave.webp",
  "lingli-chat.webp": "bio-v3/assets/f36f433f84351fbf/materials/lingli-chat.webp"
};
